---
# tasks file for test_role2

- name: template a file
  ansible.builtin.template:
    src: templates/template.txt.j2
    dest: /tmp/template.txt

- name: slurp the content of template
  ansible.builtin.slurp:
    src: /tmp/template.txt
  register: output

- name: output
  ansible.builtin.debug:
    msg: "{{ output.content | b64decode }}"